// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv44I7h1g09G4QKrKj-iDzkJRa1gsWe_s',
    appId: '1:182028714542:web:48d16be4547eff3bc6d5bf',
    messagingSenderId: '182028714542',
    projectId: 'fir-fcm-d683d',
    authDomain: 'fir-fcm-d683d.firebaseapp.com',
    databaseURL: 'https://fir-fcm-d683d-default-rtdb.firebaseio.com',
    storageBucket: 'fir-fcm-d683d.appspot.com',
    measurementId: 'G-FV2H4R0CLK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZxRlEZ5FNT2U4E_hQoCJB9GNcBzbJH-I',
    appId: '1:182028714542:android:7df4b893c43a8725c6d5bf',
    messagingSenderId: '182028714542',
    projectId: 'fir-fcm-d683d',
    databaseURL: 'https://fir-fcm-d683d-default-rtdb.firebaseio.com',
    storageBucket: 'fir-fcm-d683d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVsjWdZsttgQ7a8e4-ASCYWDWqMzMrw6o',
    appId: '1:182028714542:ios:58e6f25e3c9e2876c6d5bf',
    messagingSenderId: '182028714542',
    projectId: 'fir-fcm-d683d',
    databaseURL: 'https://fir-fcm-d683d-default-rtdb.firebaseio.com',
    storageBucket: 'fir-fcm-d683d.appspot.com',
    iosBundleId: 'com.lyngo.demoFcmApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVsjWdZsttgQ7a8e4-ASCYWDWqMzMrw6o',
    appId: '1:182028714542:ios:ab9c8d655c40e348c6d5bf',
    messagingSenderId: '182028714542',
    projectId: 'fir-fcm-d683d',
    databaseURL: 'https://fir-fcm-d683d-default-rtdb.firebaseio.com',
    storageBucket: 'fir-fcm-d683d.appspot.com',
    iosBundleId: 'com.lyngo.demoFcmApp.RunnerTests',
  );
}
